-d /nfs/home/ruilourenco.it/Documents/Code/Mule_Slant/LightFields/greek/
-o ./0.02/greek_0.02.comp
-l 9 9 64 64
-m 9 9 4 4
-lambda 10140
-r -3.1 3.5
-extension-repeat
-bt601
-VV
-preSlantTan 0
-grid_search 20
