-d /nfs/home/ruilourenco.it/Documents/Code/Mule_Slant/LightFields/greek/
-o ./debug/greek_debug.comp
-l 9 9 8 8
-m 4 4 4 4
-lambda 5
-r -3.1 3.5
-extension-repeat
-bt601
-VV
-preSlantTan 0
-grid_search 5
