-d /nfs/home/ruilourenco.it/Documents/Code/Mule_Slant/LightFields/Fountain_Vincent2/
-o ./0.02/fountain_0.02.comp
-l 13 13 128 128
-m 13 13 4 4
-nv 13
-nh 13
-off_v 1
-off_h 1
-lambda 37914
-t_gain 1
-r -0.3 0.3
-extension-repeat
-bt601
-VV
-lenslet13x13
-preSlantTan 0
-covariance
