-d /nfs/home/ruilourenco.it/Documents/Code/Mule_Slant/LightFields/Danger_de_Mort/
-o ./0.75/danger_de_mort_0.75.comp
-l 13 13 128 128
-m 13 13 4 4
-nv 13
-nh 13
-off_v 1
-off_h 1
-lambda 316
-t_gain 1
-r -0.177 0.177
-extension-repeat
-bt601
-VV
-lenslet13x13
-preSlantTan 0
-logdet 5
