-d /nfs/home/ruilourenco.it/Documents/Code/Mule_Slant/LightFields/Bikes/
-o ./0.75/bikes_0.75.comp
-l 13 13 128 128
-m 13 13 4 4
-nv 13
-nh 13
-off_v 1
-off_h 1
-lambda 258
-t_gain 1
-r -0.177 0.177
-extension-repeat
-bt601
-VV
-lenslet13x13
-preSlantTan 0
-refine_structure_tensor 10 5
