-d /nfs/home/ruilourenco.it/Documents/Code/Mule_Slant/LightFields/sideboard/
-o ./0.75/sideboard_0.75.comp
-l 9 9 64 64
-m 9 9 4 4
-lambda 200
-r -1.7 2.0
-extension-repeat
-bt601
-VV
-preSlantTan 0
-covariance
