-d /nfs/home/ruilourenco.it/Documents/Code/Mule_Slant/LightFields/Tarot/
-o ./0.1/tarot_0.1.comp
-l 17 17 128 128
-m 17 17 4 4
-nv 17
-nh 17
-lambda 1406
-r -5 5
-extenscdion-repeat
-bt601
-VV
-preSlantTan 0
-zero
