#!/usr/bin/env python3
"""Regenerate the figures of docs/structure_tensor_investigation.md.

Every figure is written twice from the same data:
  - <name>.pdf / <name>.png, rendered with matplotlib, and
  - <name>.tex, a pgfplots `tikzpicture` with the data inline, for \\input into LaTeX.

The .tex files need only `\\usepackage{pgfplots}` (and `\\pgfplotsset{compat=1.17}` or newer).
Two-panel figures are written as one .tex file per panel, to place with subfigures.

Usage:
  report_figures.py --synthetic RESULTS/synthetic/synthetic.csv \\
                    --accuracy-before OLD/accuracy_Y/accuracy_units.csv \\
                    --accuracy-after NEW/accuracy_all/accuracy_units.csv \\
                    --runs NEW/greek_crop -o docs/figures
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent))
import orientation_ablation as oa  # noqa: E402

COHERENCE_EDGES = [0, 0.1, 0.2, 0.3, 0.5, 0.7, 0.9, 1.0001]
LABELS = {
    "pooled": "Pooled",
    "per_direction": "Per-direction",
    "eigen4d": "4D eigenvector",
    "legacy": "Current method",
    "pooled_hv": "Pooled + H/V",
    "reference": "Grid search (reference)",
}
MARKS = {"pooled": "*", "per_direction": "square*", "eigen4d": "triangle*", "legacy": "diamond*",
         "pooled_hv": "pentagon*", "reference": "o"}


# --------------------------------------------------------------------------- #
# pgfplots writer
# --------------------------------------------------------------------------- #

def _num(x: float) -> str:
    return f"{x:.6g}"


def write_pgf_lines(path: Path, series: list, xlabel: str, ylabel: str, title: str = "",
                    xlog: bool = False, extra_axis: str = "", identity: tuple | None = None) -> None:
    """series: list of (label, mark, [(x, y), ...]); non-finite points are skipped."""
    opts = [r"width=\linewidth", r"height=0.75\linewidth", f"xlabel={{{xlabel}}}", f"ylabel={{{ylabel}}}",
            "grid=major", "legend pos=north west", "legend cell align=left",
            r"legend style={font=\footnotesize}"]
    if title:
        opts.append(f"title={{{title}}}")
    if xlog:
        opts.append("xmode=log")
    if extra_axis:
        opts.append(extra_axis)
    lines = ["% Generated by scripts/report_figures.py; data inline.", r"\begin{tikzpicture}",
             r"\begin{axis}[" + ", ".join(opts) + "]"]
    if identity is not None:
        lo, hi = identity
        lines.append(rf"\addplot[gray, thin, domain={_num(lo)}:{_num(hi)}] {{x}};")
        lines.append(r"\addlegendentry{true}")
    for label, mark, points in series:
        pts = " ".join(f"({_num(x)},{_num(y)})" for x, y in points if math.isfinite(x) and math.isfinite(y))
        if not pts:
            continue
        lines.append(rf"\addplot+[mark={mark}, mark size=1.5pt] coordinates {{{pts}}};")
        lines.append(rf"\addlegendentry{{{label}}}")
    lines += [r"\end{axis}", r"\end{tikzpicture}", ""]
    path.write_text("\n".join(lines))


def write_pgf_bars(path: Path, groups: list, tick_labels: list, series: list, ylabel: str, title: str = "") -> None:
    """groups: plain identifiers; tick_labels: what to print; series: (label, [value per group])."""
    sym = ",".join(groups)
    opts = [r"width=\linewidth", r"height=0.6\linewidth", "ybar", "bar width=9pt", f"ylabel={{{ylabel}}}",
            f"symbolic x coords={{{sym}}}", "xtick=data", f"xticklabels={{{', '.join(tick_labels)}}}",
            "nodes near coords",
            r"nodes near coords style={font=\scriptsize, /pgf/number format/fixed, /pgf/number format/precision=2}",
            "ymin=0", "enlarge x limits=0.25", "legend pos=north west", "legend cell align=left",
            r"legend style={font=\footnotesize}", "ymajorgrids"]
    if title:
        opts.append(f"title={{{title}}}")
    lines = ["% Generated by scripts/report_figures.py; data inline.", r"\begin{tikzpicture}",
             r"\begin{axis}[" + ", ".join(opts) + "]"]
    for label, values in series:
        pts = " ".join(f"({g},{_num(v)})" for g, v in zip(groups, values))
        lines.append(rf"\addplot coordinates {{{pts}}};")
        lines.append(rf"\addlegendentry{{{label}}}")
    lines += [r"\end{axis}", r"\end{tikzpicture}", ""]
    path.write_text("\n".join(lines))


def _pyplot():
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    return plt


def _save(fig, out: Path, name: str) -> None:
    fig.tight_layout()
    fig.savefig(out / f"{name}.pdf")
    fig.savefig(out / f"{name}.png", dpi=150)


# --------------------------------------------------------------------------- #
# Figures
# --------------------------------------------------------------------------- #

def synthetic_figure(csv_path: Path, out: Path) -> None:
    rows = list(csv.DictReader(open(csv_path)))
    plt = _pyplot()
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.5), sharey=True)
    for ax, texture in zip(axes, ("isotropic", "one_directional")):
        sub = [r for r in rows if r["texture"] == texture]
        truth = sorted({float(r["true"]) for r in sub})
        series = []
        for name in ("pooled", "per_direction", "eigen4d"):
            med = [float(np.nanmedian([float(r[name]) for r in sub if float(r["true"]) == t])) for t in truth]
            series.append((LABELS[name], MARKS[name], list(zip(truth, med))))
            ax.plot(truth, med, marker="o", markersize=3, linewidth=1, label=LABELS[name])
        ax.plot(truth, truth, color="0.6", linewidth=1, label="true")
        title = texture.replace("_", "-") + " texture"
        ax.set_title(title)
        ax.set_xlabel("true orientation arctan(d) (degrees)")
        ax.grid(True, alpha=0.3)
        write_pgf_lines(out / f"synthetic_{texture}.tex", series,
                        r"true orientation $\arctan d$ (degrees)", "estimated orientation (degrees)",
                        title=title, identity=(min(truth), max(truth)))
    axes[0].set_ylabel("estimated orientation (degrees)")
    axes[0].legend()
    _save(fig, out, "synthetic")


def _binned_medians(rows: list, key: str):
    centers, values = [], []
    for lo, hi in zip(COHERENCE_EDGES[:-1], COHERENCE_EDGES[1:]):
        sel = [float(r[key]) for r in rows if lo <= float(r["coherence"]) < hi and r.get(key, "") not in ("", "nan")]
        sel = [v for v in sel if math.isfinite(v)]
        if sel:
            centers.append((lo + min(hi, 1.0)) / 2)
            values.append(float(np.median(sel)))
    return centers, values


def accuracy_figure(csv_path: Path, out: Path, name: str, methods: list) -> None:
    rows = list(csv.DictReader(open(csv_path)))
    methods = [m for m in methods if any(r.get(m + "_error", "") not in ("", "nan") for r in rows)]
    plt = _pyplot()
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.2))
    for idx, (suffix, ylabel, scale) in enumerate((("_error", "median angular error (degrees)", 1.0),
                                                  ("_excess", "median relative RD excess (%)", 100.0))):
        series = []
        for m in methods:
            x, y = _binned_medians(rows, m + suffix)
            y = [v * scale for v in y]
            axes[idx].plot(x, y, marker="o", label=LABELS[m])
            series.append((LABELS[m], MARKS[m], list(zip(x, y))))
        axes[idx].set_xlabel("coherence")
        axes[idx].set_ylabel(ylabel)
        axes[idx].grid(True, alpha=0.3)
        write_pgf_lines(out / f"{name}_{'error' if idx == 0 else 'excess'}.tex", series, "coherence", ylabel,
                        extra_axis="legend pos=north east")
    axes[0].legend()
    _save(fig, out, name)


def _rd_points(runs: Path) -> dict:
    points = {}
    for d in runs.iterdir():
        if (d / "run.json").exists():
            n = json.loads((d / "run.json").read_text())["name"]
            points.setdefault(n, []).append(oa.rd_point(d))
    return points


def rd_figure(runs: Path, out: Path) -> None:
    points = _rd_points(runs)
    panels = [("rd_curves_wide", "Default refinement (±10°)", ["reference", "legacy", "pooled", "pooled_hv"]),
              ("rd_curves_narrow", "Narrow refinement (±2°)", ["reference", "legacy@r2", "pooled@r2", "pooled_hv@r2"])]
    plt = _pyplot()
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.3))
    for ax, (name, title, names) in zip(axes, panels):
        series = []
        for n in names:
            base = n.split("@")[0]
            p = sorted(points[n], key=lambda q: q["bpp"])
            xy = [(q["bpp"], q["psnr_yuv"]) for q in p]
            ax.plot(*zip(*xy), marker="o", markersize=3, label=LABELS[base],
                    color="k" if base == "reference" else None)
            series.append((LABELS[base], MARKS[base], xy))
        ax.set_xscale("log")
        ax.set_xlabel("bits per sample")
        ax.set_ylabel("PSNR-YUV (dB)")
        ax.set_title(title)
        ax.grid(True, which="both", alpha=0.3)
        ax.legend(fontsize=8)
        write_pgf_lines(out / f"{name}.tex", series, "bits per sample", "PSNR-YUV (dB)",
                        title=title.replace("±", r"$\pm$").replace("°", r"$^\circ$"), xlog=True,
                        extra_axis="legend pos=south east")
    _save(fig, out, "rd_curves_after_fixes")


def bdrate_figure(runs: Path, out: Path) -> None:
    points = _rd_points(runs)
    anchor = sorted(points["reference"], key=lambda p: p["bpp"])

    def bd(name):
        test = sorted(points[name], key=lambda p: p["bpp"])
        return oa.bd_rate([p["bpp"] for p in anchor], [p["psnr_yuv"] for p in anchor],
                          [p["bpp"] for p in test], [p["psnr_yuv"] for p in test])

    methods = ["legacy", "pooled", "pooled_hv"]
    configs = [("", r"$\pm10^\circ$ refinement, zero padding"),
               ("@rep", r"$\pm10^\circ$ refinement, replicate padding"),
               ("@r2", r"$\pm2^\circ$ refinement, zero padding")]
    values = [[bd(m + tag) for m in methods] for tag, _ in configs]
    groups = ["current", "pooled", "pooledhv"]

    plt = _pyplot()
    fig, ax = plt.subplots(figsize=(7, 4))
    x = np.arange(len(methods))
    width = 0.26
    for i, ((_, label), vals) in enumerate(zip(configs, values)):
        bars = ax.bar(x + (i - 1) * width, vals, width,
                      label=label.replace(r"$\pm", "±").replace(r"^\circ$", "°"))
        ax.bar_label(bars, fmt="%.2f", fontsize=8)
    ax.set_xticks(x)
    ax.set_xticklabels(["Current method", "Pooled", "Pooled + H/V"])
    ax.set_ylabel("BD-rate vs grid search (%), PSNR-YUV")
    ax.legend(fontsize=8)
    ax.grid(True, axis="y", alpha=0.3)
    _save(fig, out, "bdrate_after_fixes")
    write_pgf_bars(out / "bdrate_after_fixes.tex", groups, ["Current method", "Pooled", "Pooled + H/V"],
                   [(label, vals) for (_, label), vals in zip(configs, values)],
                   "BD-rate vs grid search (\\%), PSNR-YUV")


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--synthetic", type=Path)
    parser.add_argument("--accuracy-before", type=Path)
    parser.add_argument("--accuracy-after", type=Path)
    parser.add_argument("--runs", type=Path, help="run directory of the post-fix ablation")
    parser.add_argument("-o", "--output", type=Path, required=True)
    args = parser.parse_args(argv)
    args.output.mkdir(parents=True, exist_ok=True)
    if args.synthetic:
        synthetic_figure(args.synthetic, args.output)
    if args.accuracy_before:
        accuracy_figure(args.accuracy_before, args.output, "accuracy_vs_coherence_before_fixes",
                        ["pooled", "per_direction", "eigen4d"])
    if args.accuracy_after:
        accuracy_figure(args.accuracy_after, args.output, "accuracy_vs_coherence_after_fixes",
                        ["pooled", "per_direction", "eigen4d", "legacy", "pooled_hv"])
    if args.runs:
        rd_figure(args.runs, args.output)
        bdrate_figure(args.runs, args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
