-d /nfs/home/ruilourenco.it/Documents/Code/Mule_Slant/LightFields/poznanlab1_TAU
-o ./0.05/lab1_0.05.comp
-l 31 31 128 128
-m 31 31 4 4
-nv 31
-nh 31
-lambda 7506
-r -4.1 4.2
-extenscdion-repeat
-bt601
-t_gain 0.00390625
-VV
-preSlantTan 0
-refine_structure_tensor 10 5
